### ISSUE TITLE
As a developer I want to fix the bug where my cheeps don't show up on my timeline unless I start following someone

### ISSUE THREAD

**Issue by Olivia-Brophy** [ITU-BDSA2024-GROUP22/Chirp#209]

**Comment by AyushAnand123manipal** [comment]
you need to fix the system to make sure it always show your cheeps, not just the ones from people you follow.
issues can be 
1.When your posts are saved, the system might be set up to only show posts from other people you follow. It might not include your own posts in the timeline. The system needs to be adjusted so that it shows your posts as well, even if you're not following anyone.
2.If the data is fetched correctly but your posts still don't appear, it could be a problem with how the app shows the posts. Maybe the system isn't updating or displaying your posts on the screen properly.
